apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: python-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: python-api=ghcr.io/ahmeddayah26/redis-fastapi-assignment/python-api
    argocd-image-updater.argoproj.io/python-api.update-strategy: newest-build
    argocd-image-updater.argoproj.io/python-api.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/python-api.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git

spec:

  project: default

  source:
    repoURL: https://github.com/ahmeddayah26/redis-fastapi-assignment.git

    targetRevision: main

    path: helm/python-api

    helm:
      valueFiles:
        - values.yaml


  destination:
    server: https://kubernetes.default.svc

    namespace: default


  syncPolicy:

    automated:

      prune: true

      selfHeal: true

    syncOptions:
      - CreateNamespace=true
