helm:
  parameters:
  - name: image.repository
    value: ghcr.io/ahmeddayah26/redis-fastapi-assignment/python-api
    forcestring: true
  - name: image.tag
    value: 2c8ecdbd0bee1c4f8cdcba7d3875dd2385536f19
    forcestring: true
