helm:
  parameters:
  - name: image.repository
    value: ghcr.io/ahmeddayah26/redis-fastapi-assignment/python-api
    forcestring: true
  - name: image.tag
    value: 8d314bc0bd5b245325ef6d17c6ae93e7ec35f76b
    forcestring: true
