helm:
  parameters:
  - name: image.repository
    value: ghcr.io/ahmeddayah26/redis-fastapi-assignment/python-api
    forcestring: true
  - name: image.tag
    value: c82757537562f1fa32dfc853980013306a944b3c
    forcestring: true
