replicaCount: 1

image:
  repository: ghcr.io/ahmeddayah26/redis-fastapi-assignment/python-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: localhost

redis:
  host: redis
  port: 6379

secret:
  password: redis-123

persistence:
  storage: 1Gi
